#!/bin/bash

source /var/mipt/common_utils

# Прекратить выполнения скрипта при возникновении хоть одной ошибки
set -e

echo "Программа по изменению SVN-пароля студента."
author_info

STUDENT=
PASSWORD=
echo "Введите существующий username студента."
echo "Если такового не существует - воспользуйтесь командой mipt_add_student."
echo

# TODO распечатать доступные юзернеймы?

read -p "Username: " STUDENT

# На всякий случай проверим формат юзернейма, чтобы не надо было экранировать
# символы в дальнейшем.
check_username_format "$STUDENT"

if grep -q "^$STUDENT=" ~/passwd
then
  true
else
  echo "ОШИБКА: Такого username нету в файле ~/passwd!"
  exit 1
fi

password_unencrypted_warning
read -s -p "Введите новый пароль студента (минимум 8 символов): " PASSWORD; echo
check_password "$PASSWORD" "$PASSWORD"
read -s -p "Введите еще раз: " PASSWORD2; echo
check_password "$PASSWORD" "$PASSWORD2"

sed --follow-symlinks -i "s/^$STUDENT=.*/$STUDENT=$PASSWORD/" ~/passwd
echo "Готово!"
