#!/bin/bash

# change_password - a script to change a password in a SVN passwd file.
# Copyright (C) 2012 Timur Iskhodzhanov timurrrr+miptsvn@gmail.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /var/mipt/common_utils

# Прекратить выполнения скрипта при возникновении хоть одной ошибки
set -e

echo "Программа по изменению SVN-пароля студента."
author_info

STUDENT=
PASSWORD=
echo "Введите существующий username студента."
echo "Если такового не существует - воспользуйтесь командой mipt_add_student."
echo

# TODO распечатать доступные юзернеймы?

read -p "Username: " STUDENT

# На всякий случай проверим формат юзернейма, чтобы не надо было экранировать
# символы в дальнейшем.
check_username_format "$STUDENT"

if grep -q "^$STUDENT=" ~/passwd
then
  true
else
  echo "ОШИБКА: Такого username нету в файле ~/passwd!"
  exit 1
fi

password_unencrypted_warning
read -s -p "Введите новый пароль студента (минимум 8 символов): " PASSWORD; echo
check_password "$PASSWORD" "$PASSWORD"
read -s -p "Введите еще раз: " PASSWORD2; echo
check_password "$PASSWORD" "$PASSWORD2"

sed --follow-symlinks -i "s/^$STUDENT=.*/$STUDENT=$PASSWORD/" ~/passwd
echo "Готово!"
