#!/bin/bash

# add_student - a script to add a student to passwd/authz files.
# Copyright (C) 2012 Timur Iskhodzhanov timurrrr+miptsvn@gmail.com

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

source /var/mipt/common_utils

# Прекратить выполнения скрипта при возникновении хоть одной ошибки
set -e

echo "Программа по добавлению доступа к SVN студенту."
author_info

STUDENT=
PASSWORD=
echo "Введите username студента (латиницей, в нижнем регистре)."
echo "Если в группе есть однофамильцы - рекомендуется добавлять инициалы или цифры."
echo
read -p "Username: " STUDENT
check_username_format "$STUDENT"
check_user_doesnt_exist "$STUDENT"

password_unencrypted_warning
read -s -p "Введите пароль студента (минимум 8 символов): " PASSWORD; echo
check_password "$PASSWORD" "$PASSWORD"
read -s -p "Введите еще раз: " PASSWORD2; echo
check_password "$PASSWORD" "$PASSWORD2"

# На всякий случай, ещё разок проверим...
check_user_doesnt_exist "$STUDENT"

echo "$STUDENT=$PASSWORD" >> ~/passwd
cat >> ~/authz <<EOF

[/$STUDENT]
$STUDENT = rw
EOF

echo "Готово!"
echo
echo "ВАЖНО: Преподаватель, не забудьте создать новому студенту личную папку!"
echo "Для этого, выполните в корневой папке Вашего SVN-клиента"
echo "следующие команды:"
echo "  mkdir $STUDENT"
echo "  svn add $STUDENT"
echo "  svn commit $STUDENT -m \"Personal directory for $STUDENT\""
